bids_dir: 'bids'
seg_bids:
  funcmasker: 'bids_funcmasker'
  rutherford: 'bids_rutherford'

methods:
  - funcmasker
  - rutherford
  - bet # bet is run in this workflow, instead of grabbed from bids

pybids_inputs:
  mask:
    filters:
      suffix: 'mask'
      extension: '.nii.gz'
      datatype: 'func'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run

  bold:
    filters:
      suffix: 'bold'
      extension: '.nii.gz'
      datatype: 'func'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run



pybids_inputs_seg:
  mask:
    filters:
      suffix: 'mask'
      extension: '.nii.gz'
      datatype: 'func'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run


